<a href="https://colab.research.google.com/github/soonho123/2026-1-BDA-my-code/blob/main/%EB%B9%85%EB%8D%B0%EC%9D%B4%ED%84%B0_%EB%B6%84%EC%84%9D_6%EC%A3%BC%EC%B0%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 07 데이터프레임 정보와 검색 활용

## section 01 데이터프레임 정보와 조건 검색

In [ ]:
import pandas as pd

df = pd.read_csv('data/2016년졸음운전.csv',
                 encoding='euc-kr', index_col=0)
df

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     174      6    328
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [ ]:
df.dtypes

사고(건)    int64
사망(명)    int64
부상(명)    int64
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12 entries, 2016년1월 to 2016년12월
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   사고(건)   12 non-null     int64
 1   사망(명)   12 non-null     int64
 2   부상(명)   12 non-null     int64
dtypes: int64(3)
memory usage: 384.0+ bytes

In [ ]:
df.describe()

            사고(건)      사망(명)       부상(명)
count   12.000000  12.000000   12.000000
mean   202.750000   8.166667  408.250000
std     23.014324   3.186144   60.051682
min    168.000000   4.000000  328.000000
25%    186.000000   5.750000  363.500000
50%    200.000000   7.000000  402.500000
75%    219.500000  10.500000  441.250000
max    239.000000  13.000000  522.000000

In [ ]:
df.T

연월,2016년1월,2016년2월,2016년3월,2016년4월,2016년5월,2016년6월,2016년7월,2016년8월,2016년9월,2016년10월,2016년11월,2016년12월
사고(건),192,174,217,216,239,200,227,230,187,183,200,168
사망(명),5,6,7,7,13,12,9,7,13,10,5,4
부상(명),387,328,435,419,522,362,460,490,347,367,418,364

### 데이터프레임 합 계산

In [ ]:
df.sum()

사고(건)    2433
사망(명)      98
부상(명)    4899
dtype: int64

In [ ]:
df.sum(axis=0)

사고(건)    2433
사망(명)      98
부상(명)    4899
dtype: int64

In [ ]:
df.sum(axis=1)

연월
2016년1월     584
2016년2월     508
2016년3월     659
2016년4월     642
2016년5월     774
2016년6월     574
2016년7월     696
2016년8월     727
2016년9월     547
2016년10월    560
2016년11월    623
2016년12월    536
dtype: int64

In [ ]:
df.cumsum(axis=0)

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     366     11    715
2016년3월     583     18   1150
2016년4월     799     25   1569
2016년5월    1038     38   2091
2016년6월    1238     50   2453
2016년7월    1465     59   2913
2016년8월    1695     66   3403
2016년9월    1882     79   3750
2016년10월   2065     89   4117
2016년11월   2265     94   4535
2016년12월   2433     98   4899

In [ ]:
df.cumsum(axis=1)

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192    197    584
2016년2월     174    180    508
2016년3월     217    224    659
2016년4월     216    223    642
2016년5월     239    252    774
2016년6월     200    212    574
2016년7월     227    236    696
2016년8월     230    237    727
2016년9월     187    200    547
2016년10월    183    193    560
2016년11월    200    205    623
2016년12월    168    172    536

#### 데이터프레임 평균 계산

In [ ]:
df.mean()

사고(건)    202.750000
사망(명)      8.166667
부상(명)    408.250000
dtype: float64

In [ ]:
df.mean(axis=0)

사고(건)    202.750000
사망(명)      8.166667
부상(명)    408.250000
dtype: float64

In [ ]:
df.mean(axis=1)

연월
2016년1월     194.666667
2016년2월     169.333333
2016년3월     219.666667
2016년4월     214.000000
2016년5월     258.000000
2016년6월     191.333333
2016년7월     232.000000
2016년8월     242.333333
2016년9월     182.333333
2016년10월    186.666667
2016년11월    207.666667
2016년12월    178.666667
dtype: float64

In [ ]:
df.mean(axis=None)

206.38888888888889

### 데이터프레임 최대 최소 계산

In [ ]:
df.max()

사고(건)    239
사망(명)     13
부상(명)    522
dtype: int64

In [ ]:
df.max(axis=0)

사고(건)    239
사망(명)     13
부상(명)    522
dtype: int64

In [ ]:
df.max(axis=1)

연월
2016년1월     387
2016년2월     328
2016년3월     435
2016년4월     419
2016년5월     522
2016년6월     362
2016년7월     460
2016년8월     490
2016년9월     347
2016년10월    367
2016년11월    418
2016년12월    364
dtype: int64

In [ ]:
df.max(axis=None)

522

In [ ]:
df.min()

사고(건)    168
사망(명)      4
부상(명)    328
dtype: int64

In [ ]:
df.min(axis=0)

사고(건)    168
사망(명)      4
부상(명)    328
dtype: int64

In [ ]:
df.min(axis=1)

연월
2016년1월      5
2016년2월      6
2016년3월      7
2016년4월      7
2016년5월     13
2016년6월     12
2016년7월      9
2016년8월      7
2016년9월     13
2016년10월    10
2016년11월     5
2016년12월     4
dtype: int64

In [ ]:
df.min(axis=None)

4

### 데이터프레임 수정 대입

In [ ]:
df[['사망(명)', '부상(명)']].sum(axis=1)

연월
2016년1월     392
2016년2월     334
2016년3월     442
2016년4월     426
2016년5월     535
2016년6월     374
2016년7월     469
2016년8월     497
2016년9월     360
2016년10월    377
2016년11월    423
2016년12월    368
dtype: int64

In [ ]:
df.iloc[:, 1:].sum(axis=1)

연월
2016년1월     392
2016년2월     334
2016년3월     442
2016년4월     426
2016년5월     535
2016년6월     374
2016년7월     469
2016년8월     497
2016년9월     360
2016년10월    377
2016년11월    423
2016년12월    368
dtype: int64

In [ ]:
df2 = df.copy()
df2['재해자수'] = df[['사망(명)', '부상(명)']].sum(axis=1)
df2

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월     192      5    387   392
2016년2월     174      6    328   334
2016년3월     217      7    435   442
2016년4월     216      7    419   426
2016년5월     239     13    522   535
2016년6월     200     12    362   374
2016년7월     227      9    460   469
2016년8월     230      7    490   497
2016년9월     187     13    347   360
2016년10월    183     10    367   377
2016년11월    200      5    418   423
2016년12월    168      4    364   368

In [ ]:
df2.sum()

사고(건)    2433
사망(명)      98
부상(명)    4899
재해자수     4997
dtype: int64

In [ ]:
df2.loc['총계'] = df2.sum(axis=0)
df2

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월     192      5    387   392
2016년2월     174      6    328   334
2016년3월     217      7    435   442
2016년4월     216      7    419   426
2016년5월     239     13    522   535
2016년6월     200     12    362   374
2016년7월     227      9    460   469
2016년8월     230      7    490   497
2016년9월     187     13    347   360
2016년10월    183     10    367   377
2016년11월    200      5    418   423
2016년12월    168      4    364   368
총계         4866    196   9798  9994

#### 블리안 인덱싱

In [ ]:
df2 > 10

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월    True  False   True  True
2016년2월    True  False   True  True
2016년3월    True  False   True  True
2016년4월    True  False   True  True
2016년5월    True   True   True  True
2016년6월    True   True   True  True
2016년7월    True  False   True  True
2016년8월    True  False   True  True
2016년9월    True   True   True  True
2016년10월   True  False   True  True
2016년11월   True  False   True  True
2016년12월   True  False   True  True
총계         True   True   True  True

In [ ]:
df2[df2 > 10]

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월     192    NaN    387   392
2016년2월     174    NaN    328   334
2016년3월     217    NaN    435   442
2016년4월     216    NaN    419   426
2016년5월     239   13.0    522   535
2016년6월     200   12.0    362   374
2016년7월     227    NaN    460   469
2016년8월     230    NaN    490   497
2016년9월     187   13.0    347   360
2016년10월    183    NaN    367   377
2016년11월    200    NaN    418   423
2016년12월    168    NaN    364   368
총계         4866  196.0   9798  9994

In [ ]:
df2[ [True]*6 + [False]*7 ]

         사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월    192      5    387   392
2016년2월    174      6    328   334
2016년3월    217      7    435   442
2016년4월    216      7    419   426
2016년5월    239     13    522   535
2016년6월    200     12    362   374

In [ ]:
df2['재해자수'] > 400

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월      True
2016년6월     False
2016년7월      True
2016년8월      True
2016년9월     False
2016년10월    False
2016년11월     True
2016년12월    False
총계           True
Name: 재해자수, dtype: bool

In [ ]:
df2[df2['재해자수'] > 400]

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년3월     217      7    435   442
2016년4월     216      7    419   426
2016년5월     239     13    522   535
2016년7월     227      9    460   469
2016년8월     230      7    490   497
2016년11월    200      5    418   423
총계         2433     98   4899  4997

In [ ]:
df['사망(명)'] == 7

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월     False
2016년6월     False
2016년7월     False
2016년8월      True
2016년9월     False
2016년10월    False
2016년11월    False
2016년12월    False
Name: 사망(명), dtype: bool

In [ ]:
df['사망(명)'].isin([7])

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월     False
2016년6월     False
2016년7월     False
2016년8월      True
2016년9월     False
2016년10월    False
2016년11월    False
2016년12월    False
Name: 사망(명), dtype: bool

In [ ]:
df['사망(명)'].isin([7, 10])

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월     False
2016년6월     False
2016년7월     False
2016년8월      True
2016년9월     False
2016년10월     True
2016년11월    False
2016년12월    False
Name: 사망(명), dtype: bool

In [ ]:
df[ df['사망(명)'].isin([7, 10]) ]

          사고(건)  사망(명)  부상(명)
연월
2016년3월     217      7    435
2016년4월     216      7    419
2016년8월     230      7    490
2016년10월    183     10    367

In [ ]:
df[ (df['사망(명)'].isin([7, 10])) | (df['부상(명)'] > 350) ]

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [ ]:
df[ df.index.str.contains('3') ]

         사고(건)  사망(명)  부상(명)
연월
2016년3월    217      7    435

### 블리안 인덱싱으로 값 대입

In [ ]:
df3 = df.copy()
df3

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     174      6    328
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [ ]:
df3[df3 > 10] = -df3
df3

          사고(건)  사망(명)  부상(명)
연월
2016년1월    -192      5   -387
2016년2월    -174      6   -328
2016년3월    -217      7   -435
2016년4월    -216      7   -419
2016년5월    -239    -13   -522
2016년6월    -200    -12   -362
2016년7월    -227      9   -460
2016년8월    -230      7   -490
2016년9월    -187    -13   -347
2016년10월   -183     10   -367
2016년11월   -200      5   -418
2016년12월   -168      4   -364

#### 함수 df.query(조건)

In [ ]:
df = pd.DataFrame({'A': range(1, 6),
                   'B': range(6, -3, -2),
                   'C': range(10, 5, -1),
                   'D clmns': range(3, -2, -1),
                   'E': ['python', 'java', 'python', 'go', 'python']})
df

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python

In [ ]:
df.query('A > B')

   A  B  C  D clmns       E
2  3  2  8        1  python
3  4  0  7        0      go
4  5 -2  6       -1  python

In [ ]:
df[df.A > df.B]

   A  B  C  D clmns       E
2  3  2  8        1  python
3  4  0  7        0      go
4  5 -2  6       -1  python

In [ ]:
df.query('C == 10')

   A  B   C  D clmns       E
0  1  6  10        3  python

In [ ]:
df.query('A > 0')

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python

In [ ]:
df.query('E == "python"')

   A  B   C  D clmns       E
0  1  6  10        3  python
2  3  2   8        1  python
4  5 -2   6       -1  python

In [ ]:
df.query("E != 'python'")

   A  B  C  D clmns     E
1  2  4  9        2  java
3  4  0  7        0    go

In [ ]:
df.query('A == `D clmns`')

   A  B  C  D clmns     E
1  2  4  9        2  java

In [ ]:
df.query('A == "D clmns"')

Empty DataFrame
Columns: [A, B, C, D clmns, E]
Index: []

In [ ]:
df[df.A == df["D clmns"]]

   A  B  C  D clmns     E
1  2  4  9        2  java

In [ ]:
df.query('A > 3 | B > 8')

   A  B  C  D clmns       E
3  4  0  7        0      go
4  5 -2  6       -1  python

In [ ]:
df.query('A > 2 & C < 8')

   A  B  C  D clmns       E
3  4  0  7        0      go
4  5 -2  6       -1  python

In [ ]:
df.query("E in ['python', 'go']")

   A  B   C  D clmns       E
0  1  6  10        3  python
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python

In [ ]:
num = 3
df.query('B > @num')

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java

In [ ]:
num = 3
df.query(f'B > {num}')

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java

In [ ]:
s = "E.str.contains('py')"
df.query(s)

   A  B   C  D clmns       E
0  1  6  10        3  python
2  3  2   8        1  python
4  5 -2   6       -1  python

In [ ]:
s = 'E.str.startswith("g")'
df.query(s)

   A  B  C  D clmns   E
3  4  0  7        0  go

In [ ]:
s = "E.str.endswith('on')"
df.query(s)

   A  B   C  D clmns       E
0  1  6  10        3  python
2  3  2   8        1  python
4  5 -2   6       -1  python

## section 02 데이터프레임 정렬과 수정

### 데이터프레임 앞 보기 head(n)

In [ ]:
import pandas as pd

df = pd.read_csv('data/2016년졸음운전.csv', encoding='euc-kr', index_col=0)
df

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     174      6    328
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [ ]:
df.head()

         사고(건)  사망(명)  부상(명)
연월
2016년1월    192      5    387
2016년2월    174      6    328
2016년3월    217      7    435
2016년4월    216      7    419
2016년5월    239     13    522

In [ ]:
df.head(7)

         사고(건)  사망(명)  부상(명)
연월
2016년1월    192      5    387
2016년2월    174      6    328
2016년3월    217      7    435
2016년4월    216      7    419
2016년5월    239     13    522
2016년6월    200     12    362
2016년7월    227      9    460

### 데이터프레임 뒤 보기 tail(n)

In [ ]:
df.tail()

          사고(건)  사망(명)  부상(명)
연월
2016년8월     230      7    490
2016년9월     187     13    347
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [ ]:
df.tail(6)

          사고(건)  사망(명)  부상(명)
연월
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

#### 데이터프레임 행 레이블 정렬

In [ ]:
import pandas as pd

df = pd.read_csv('data/2016년졸음운전.csv', encoding='euc-kr', index_col=0)
df

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     174      6    328
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [ ]:
df.sort_index()

          사고(건)  사망(명)  부상(명)
연월
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364
2016년1월     192      5    387
2016년2월     174      6    328
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347

In [ ]:
df.sort_index(axis=0)

          사고(건)  사망(명)  부상(명)
연월
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364
2016년1월     192      5    387
2016년2월     174      6    328
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347

In [ ]:
df.sort_index(ascending=False)

          사고(건)  사망(명)  부상(명)
연월
2016년9월     187     13    347
2016년8월     230      7    490
2016년7월     227      9    460
2016년6월     200     12    362
2016년5월     239     13    522
2016년4월     216      7    419
2016년3월     217      7    435
2016년2월     174      6    328
2016년1월     192      5    387
2016년12월    168      4    364
2016년11월    200      5    418
2016년10월    183     10    367

#### 데이터프레임 열 레이블 정렬

In [ ]:
df.sort_index(axis=1)

          부상(명)  사고(건)  사망(명)
연월
2016년1월     387    192      5
2016년2월     328    174      6
2016년3월     435    217      7
2016년4월     419    216      7
2016년5월     522    239     13
2016년6월     362    200     12
2016년7월     460    227      9
2016년8월     490    230      7
2016년9월     347    187     13
2016년10월    367    183     10
2016년11월    418    200      5
2016년12월    364    168      4

In [ ]:
df.sort_index(axis=1, ascending=False)

          사망(명)  사고(건)  부상(명)
연월
2016년1월       5    192    387
2016년2월       6    174    328
2016년3월       7    217    435
2016년4월       7    216    419
2016년5월      13    239    522
2016년6월      12    200    362
2016년7월       9    227    460
2016년8월       7    230    490
2016년9월      13    187    347
2016년10월     10    183    367
2016년11월      5    200    418
2016년12월      4    168    364

#### 데이터프레임 열 값으로 정렬

In [ ]:
df.sort_values(by='사망(명)')

          사고(건)  사망(명)  부상(명)
연월
2016년12월    168      4    364
2016년1월     192      5    387
2016년11월    200      5    418
2016년2월     174      6    328
2016년3월     217      7    435
2016년4월     216      7    419
2016년8월     230      7    490
2016년7월     227      9    460
2016년10월    183     10    367
2016년6월     200     12    362
2016년5월     239     13    522
2016년9월     187     13    347

In [ ]:
df.sort_values('사망(명)', ascending=False)

          사고(건)  사망(명)  부상(명)
연월
2016년5월     239     13    522
2016년9월     187     13    347
2016년6월     200     12    362
2016년10월    183     10    367
2016년7월     227      9    460
2016년3월     217      7    435
2016년4월     216      7    419
2016년8월     230      7    490
2016년2월     174      6    328
2016년1월     192      5    387
2016년11월    200      5    418
2016년12월    168      4    364

In [ ]:
df.sort_values(by=['사망(명)', '부상(명)'])

          사고(건)  사망(명)  부상(명)
연월
2016년12월    168      4    364
2016년1월     192      5    387
2016년11월    200      5    418
2016년2월     174      6    328
2016년4월     216      7    419
2016년3월     217      7    435
2016년8월     230      7    490
2016년7월     227      9    460
2016년10월    183     10    367
2016년6월     200     12    362
2016년9월     187     13    347
2016년5월     239     13    522

In [ ]:
df.sort_values(by=['사망(명)', '부상(명)'], ascending=False)

          사고(건)  사망(명)  부상(명)
연월
2016년5월     239     13    522
2016년9월     187     13    347
2016년6월     200     12    362
2016년10월    183     10    367
2016년7월     227      9    460
2016년8월     230      7    490
2016년3월     217      7    435
2016년4월     216      7    419
2016년2월     174      6    328
2016년11월    200      5    418
2016년1월     192      5    387
2016년12월    168      4    364

#### 데이터프레임 행 값으로 정렬

In [ ]:
df.sort_values(by='2016년12월', axis=1)

          사망(명)  사고(건)  부상(명)
연월
2016년1월       5    192    387
2016년2월       6    174    328
2016년3월       7    217    435
2016년4월       7    216    419
2016년5월      13    239    522
2016년6월      12    200    362
2016년7월       9    227    460
2016년8월       7    230    490
2016년9월      13    187    347
2016년10월     10    183    367
2016년11월      5    200    418
2016년12월      4    168    364

In [ ]:
df.sort_values(by=['2016년12월'], axis=1, ascending=False)

          부상(명)  사고(건)  사망(명)
연월
2016년1월     387    192      5
2016년2월     328    174      6
2016년3월     435    217      7
2016년4월     419    216      7
2016년5월     522    239     13
2016년6월     362    200     12
2016년7월     460    227      9
2016년8월     490    230      7
2016년9월     347    187     13
2016년10월    367    183     10
2016년11월    418    200      5
2016년12월    364    168      4

In [ ]:
import numpy as np
import pandas as pd

dates = pd.date_range("20240102", periods=6)
df = pd.DataFrame(np.arange(24).reshape(6, 4), index=dates)
df

             0   1   2   3
2024-01-02   0   1   2   3
2024-01-03   4   5   6   7
2024-01-04   8   9  10  11
2024-01-05  12  13  14  15
2024-01-06  16  17  18  19
2024-01-07  20  21  22  23

In [ ]:
df.columns = list('ABCD')
df

             A   B   C   D
2024-01-02   0   1   2   3
2024-01-03   4   5   6   7
2024-01-04   8   9  10  11
2024-01-05  12  13  14  15
2024-01-06  16  17  18  19
2024-01-07  20  21  22  23

In [ ]:
s1 = pd.Series([1, 2, 3, 4, 5], index=pd.date_range("20240102", periods=5))
s1

2024-01-02    1
2024-01-03    2
2024-01-04    3
2024-01-05    4
2024-01-06    5
Freq: D, dtype: int64

In [ ]:
df["E"] = s1
df

             A   B   C   D    E
2024-01-02   0   1   2   3  1.0
2024-01-03   4   5   6   7  2.0
2024-01-04   8   9  10  11  3.0
2024-01-05  12  13  14  15  4.0
2024-01-06  16  17  18  19  5.0
2024-01-07  20  21  22  23  NaN

#### 레이블로 값 대입

In [ ]:
df.loc['2024-01-02', 'A'] = 10
df

             A   B   C   D    E
2024-01-02  10   1   2   3  1.0
2024-01-03   4   5  60   7  2.0
2024-01-04   8   9  10  11  3.0
2024-01-05  12  13  14  15  4.0
2024-01-06  16  17  18  19  5.0
2024-01-07  20  21  22  23  NaN

In [ ]:
df.loc[dates[1], 'B'] = 50
df

             A   B   C   D    E
2024-01-02  10   1   2   3  1.0
2024-01-03   4  50  60   7  2.0
2024-01-04   8   9  10  11  3.0
2024-01-05  12  13  14  15  4.0
2024-01-06  16  17  18  19  5.0
2024-01-07  20  21  22  23  NaN

In [ ]:
df.at[dates[2], df.columns[2]] = 100
df

             A   B    C   D    E
2024-01-02  10   1    2   3  1.0
2024-01-03   4  50   60   7  2.0
2024-01-04   8   9  100  11  3.0
2024-01-05  12  13   14  15  4.0
2024-01-06  16  17   18  19  5.0
2024-01-07  20  21   22  23  NaN

In [ ]:
df.at[df.index[-1], df.columns[-1]] = 230
df

             A   B    C   D      E
2024-01-02  10   1    2   3    1.0
2024-01-03   4  50   60   7    2.0
2024-01-04   8   9  100  11    3.0
2024-01-05  12  13   14  15    4.0
2024-01-06  16  17   18  19    5.0
2024-01-07  20  21   22  23  230.0

#### 위치로 값 대입

In [ ]:
df.iloc[1, 2] = 60
df

             A   B    C   D      E
2024-01-02  10   1    2   3    1.0
2024-01-03   4  50   60   7    2.0
2024-01-04   8   9  100  11    3.0
2024-01-05  12  13   14  15    4.0
2024-01-06  16  17   18  19    5.0
2024-01-07  20  21   22  23  230.0

In [ ]:
df.iat[3, 3] = 150
df

             A   B    C    D      E
2024-01-02  10   1    2    3    1.0
2024-01-03   4  50   60    7    2.0
2024-01-04   8   9  100   11    3.0
2024-01-05  12  13   14  150    4.0
2024-01-06  16  17   18   19    5.0
2024-01-07  20  21   22   23  230.0

In [ ]:
df.iloc[:, 4] = [500] * len(df)
df

             A   B    C    D      E
2024-01-02  10   1    2    3  500.0
2024-01-03   4  50   60    7  500.0
2024-01-04   8   9  100   11  500.0
2024-01-05  12  13   14  150  500.0
2024-01-06  16  17   18   19  500.0
2024-01-07  20  21   22   23  500.0

In [ ]:
df.iloc[:, 4] = 600
df

             A   B    C    D      E
2024-01-02  10   1    2    3  600.0
2024-01-03   4  50   60    7  600.0
2024-01-04   8   9  100   11  600.0
2024-01-05  12  13   14  150  600.0
2024-01-06  16  17   18   19  600.0
2024-01-07  20  21   22   23  600.0

## (6) 결측치 처리

In [ ]:
import numpy as np
import pandas as pd

dates = pd.date_range("20250302", periods=7, freq='W-MON')
df = pd.DataFrame(np.arange(35).reshape(7, 5), index=dates, columns=list('ABCDE'))
df

             A   B   C   D   E
2025-03-03   0   1   2   3   4
2025-03-10   5   6   7   8   9
2025-03-17  10  11  12  13  14
2025-03-24  15  16  17  18  19
2025-03-31  20  21  22  23  24
2025-04-07  25  26  27  28  29
2025-04-14  30  31  32  33  34

In [ ]:
subdates = pd.date_range("20250307", periods=5, freq='W-MON')
subdates

DatetimeIndex(['2025-03-10', '2025-03-17', '2025-03-24', '2025-03-31',
               '2025-04-07'],
              dtype='datetime64[ns]', freq='W-MON')

In [ ]:
s = pd.Series(np.linspace(10, 17, 5), index=subdates)
s

2025-03-10    10.00
2025-03-17    11.75
2025-03-24    13.50
2025-03-31    15.25
2025-04-07    17.00
Freq: W-MON, dtype: float64

In [ ]:
df['F'] = s
df

             A   B   C   D   E      F
2025-03-03   0   1   2   3   4    NaN
2025-03-10   5   6   7   8   9  10.00
2025-03-17  10  11  12  13  14  11.75
2025-03-24  15  16  17  18  19  13.50
2025-03-31  20  21  22  23  24  15.25
2025-04-07  25  26  27  28  29  17.00
2025-04-14  30  31  32  33  34    NaN

In [ ]:
df2 = df.copy()
df2.iloc[3, 4] = np.nan
df2.iloc[1, :] = np.nan
df2

               A     B     C     D     E      F
2025-03-03   0.0   1.0   2.0   3.0   4.0    NaN
2025-03-10   NaN   NaN   NaN   NaN   NaN    NaN
2025-03-17  10.0  11.0  12.0  13.0  14.0  11.75
2025-03-24  15.0  16.0  17.0  18.0   NaN  13.50
2025-03-31  20.0  21.0  22.0  23.0  24.0  15.25
2025-04-07  25.0  26.0  27.0  28.0  29.0  17.00
2025-04-14  30.0  31.0  32.0  33.0  34.0    NaN

In [ ]:
pd.isna(df2)

                A      B      C      D      E      F
2025-03-03  False  False  False  False  False   True
2025-03-10   True   True   True   True   True   True
2025-03-17  False  False  False  False  False  False
2025-03-24  False  False  False  False   True  False
2025-03-31  False  False  False  False  False  False
2025-04-07  False  False  False  False  False  False
2025-04-14  False  False  False  False  False   True

In [ ]:
df2.isna()

                A      B      C      D      E      F
2025-03-03  False  False  False  False  False   True
2025-03-10   True   True   True   True   True   True
2025-03-17  False  False  False  False  False  False
2025-03-24  False  False  False  False   True  False
2025-03-31  False  False  False  False  False  False
2025-04-07  False  False  False  False  False  False
2025-04-14  False  False  False  False  False   True

In [ ]:
df2.isnull()

                A      B      C      D      E      F
2025-03-03  False  False  False  False  False   True
2025-03-10   True   True   True   True   True   True
2025-03-17  False  False  False  False  False  False
2025-03-24  False  False  False  False   True  False
2025-03-31  False  False  False  False  False  False
2025-04-07  False  False  False  False  False  False
2025-04-14  False  False  False  False  False   True

In [ ]:
df2.count()

A    6
B    6
C    6
D    6
E    5
F    4
dtype: int64

In [ ]:
df2.count(axis=1)

2025-03-03    5
2025-03-10    0
2025-03-17    6
2025-03-24    5
2025-03-31    6
2025-04-07    6
2025-04-14    5
Freq: W-MON, dtype: int64

#### value_counts()

In [ ]:
s = df2.E.value_counts()
s

E
4.0     1
14.0    1
24.0    1
29.0    1
34.0    1
Name: count, dtype: int64

In [ ]:
type(s)

pandas.core.series.Series

In [ ]:
s[4]

1

In [ ]:
s.values

array([1, 1, 1, 1, 1], dtype=int64)

In [ ]:
df2['D'].value_counts()

D
3.0     1
13.0    1
18.0    1
23.0    1
28.0    1
33.0    1
Name: count, dtype: int64

In [ ]:
df2['D'].value_counts().to_frame()

      count
D
3.0       1
13.0      1
18.0      1
23.0      1
28.0      1
33.0      1

In [ ]:
df2.E.value_counts(dropna=False)

E
NaN     2
4.0     1
14.0    1
24.0    1
29.0    1
34.0    1
Name: count, dtype: int64

In [ ]:
s1 = df2.value_counts()
s1

A     B     C     D     E     F
10.0  11.0  12.0  13.0  14.0  11.75    1
20.0  21.0  22.0  23.0  24.0  15.25    1
25.0  26.0  27.0  28.0  29.0  17.00    1
Name: count, dtype: int64

In [ ]:
s1.index

MultiIndex([(10.0, 11.0, 12.0, 13.0, 14.0, 11.75),
            (20.0, 21.0, 22.0, 23.0, 24.0, 15.25),
            (25.0, 26.0, 27.0, 28.0, 29.0,  17.0)],
           names=['A', 'B', 'C', 'D', 'E', 'F'])

In [ ]:
s1.values

array([1, 1, 1], dtype=int64)

In [ ]:
df2.value_counts(dropna=False)

A     B     C     D     E     F
0.0   1.0   2.0   3.0   4.0   NaN      1
10.0  11.0  12.0  13.0  14.0  11.75    1
15.0  16.0  17.0  18.0  NaN   13.50    1
20.0  21.0  22.0  23.0  24.0  15.25    1
25.0  26.0  27.0  28.0  29.0  17.00    1
30.0  31.0  32.0  33.0  34.0  NaN      1
NaN   NaN   NaN   NaN   NaN   NaN      1
dtype: int64

#### 함수 dropna()

In [ ]:
df2.dropna()

               A     B     C     D     E      F
2025-03-17  10.0  11.0  12.0  13.0  14.0  11.75
2025-03-31  20.0  21.0  22.0  23.0  24.0  15.25
2025-04-07  25.0  26.0  27.0  28.0  29.0  17.00

In [ ]:
df2.dropna(axis=0)

               A     B     C     D     E      F
2025-03-17  10.0  11.0  12.0  13.0  14.0  11.75
2025-03-31  20.0  21.0  22.0  23.0  24.0  15.25
2025-04-07  25.0  26.0  27.0  28.0  29.0  17.00

In [ ]:
df2.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [2025-03-03 00:00:00, 2025-03-10 00:00:00, 2025-03-17 00:00:00, 2025-03-24 00:00:00, 2025-03-31 00:00:00, 2025-04-07 00:00:00, 2025-04-14 00:00:00]

In [ ]:
df2

               A     B     C     D     E      F
2025-03-03   0.0   1.0   2.0   3.0   4.0    NaN
2025-03-10   NaN   NaN   NaN   NaN   NaN    NaN
2025-03-17  10.0  11.0  12.0  13.0  14.0  11.75
2025-03-24  15.0  16.0  17.0  18.0   NaN  13.50
2025-03-31  20.0  21.0  22.0  23.0  24.0  15.25
2025-04-07  25.0  26.0  27.0  28.0  29.0  17.00
2025-04-14  30.0  31.0  32.0  33.0  34.0    NaN

In [ ]:
df2[ df2.isna() ] = 500
df2

                A      B      C      D      E       F
2025-03-03    0.0    1.0    2.0    3.0    4.0  500.00
2025-03-10  500.0  500.0  500.0  500.0  500.0  500.00
2025-03-17   10.0   11.0   12.0   13.0   14.0   11.75
2025-03-24   15.0   16.0   17.0   18.0  500.0   13.50
2025-03-31   20.0   21.0   22.0   23.0   24.0   15.25
2025-04-07   25.0   26.0   27.0   28.0   29.0   17.00
2025-04-14   30.0   31.0   32.0   33.0   34.0  500.00

#### 결측치를 위한 함수 fillna()

In [ ]:
df = pd.DataFrame([[np.nan, 2, np.nan, 0],
                   [3, 4, np.nan, 1],
                   [np.nan, np.nan, np.nan, np.nan],
                   [np.nan, 3, np.nan, 4]],
                  columns=list("ABCD"))
df

     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  NaN
3  NaN  3.0 NaN  4.0

In [ ]:
df.fillna(10)

      A     B     C     D
0  10.0   2.0  10.0   0.0
1   3.0   4.0  10.0   1.0
2  10.0  10.0  10.0  10.0
3  10.0   3.0  10.0   4.0

In [ ]:
df

     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  NaN
3  NaN  3.0 NaN  4.0

In [ ]:
df.fillna('missing', axis=0)

         A        B        C        D
0  missing      2.0  missing      0.0
1      3.0      4.0  missing      1.0
2  missing  missing  missing  missing
3  missing      3.0  missing      4.0

In [ ]:
df.fillna('missing', limit=1)

         A        B        C        D
0  missing      2.0  missing      0.0
1      3.0      4.0      NaN      1.0
2      NaN  missing      NaN  missing
3      NaN      3.0      NaN      4.0

In [ ]:
df.fillna('missing', limit=1, axis=1)

         A    B        C    D
0  missing  2.0      NaN  0.0
1      3.0  4.0  missing  1.0
2  missing  NaN      NaN  NaN
3  missing  3.0      NaN  4.0

In [ ]:
df.fillna('value', axis=1)

       A      B      C      D
0  value    2.0  value    0.0
1    3.0    4.0  value    1.0
2  value  value  value  value
3  value    3.0  value    4.0

In [ ]:
values = {"A": 100, "B": 200, "C": 300, "D": 400}
df.fillna(value=values)

       A      B      C      D
0  100.0    2.0  300.0    0.0
1    3.0    4.0  300.0    1.0
2  100.0  200.0  300.0  400.0
3  100.0    3.0  300.0    4.0

In [ ]:
df.fillna(value=values, limit=2)

       A      B      C      D
0  100.0    2.0  300.0    0.0
1    3.0    4.0  300.0    1.0
2  100.0  200.0    NaN  400.0
3    NaN    3.0    NaN    4.0

In [ ]:
s = pd.Series([100, 200, 400], index=list('ACD'))
s

A    100
C    200
D    400
dtype: int64

In [ ]:
df.fillna(value=s, limit=1)

       A    B      C      D
0  100.0  2.0  200.0    0.0
1    3.0  4.0    NaN    1.0
2    NaN  NaN    NaN  400.0
3    NaN  3.0    NaN    4.0

In [ ]:
df2 = pd.DataFrame(-np.ones((4, 4)), columns=list("ABCE"))
df2

     A    B    C    E
0 -1.0 -1.0 -1.0 -1.0
1 -1.0 -1.0 -1.0 -1.0
2 -1.0 -1.0 -1.0 -1.0
3 -1.0 -1.0 -1.0 -1.0

In [ ]:
df.fillna(df2)

     A    B    C    D
0 -1.0  2.0 -1.0  0.0
1  3.0  4.0 -1.0  1.0
2 -1.0 -1.0 -1.0  NaN
3 -1.0  3.0 -1.0  4.0

In [ ]:
df

     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  NaN
3  NaN  3.0 NaN  4.0

In [ ]:
df.fillna(method='ffill')

C:\Users\PC\AppData\Local\Temp\ipykernel_42156\1193302488.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')

     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  3.0  4.0 NaN  1.0
3  3.0  3.0 NaN  4.0

In [ ]:
df.fillna(method='ffill', limit=1)

C:\Users\PC\AppData\Local\Temp\ipykernel_42156\3640860781.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', limit=1)

     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  3.0  4.0 NaN  1.0
3  NaN  3.0 NaN  4.0

In [ ]:
df.fillna(method='bfill', limit=1)

C:\Users\PC\AppData\Local\Temp\ipykernel_42156\3785261496.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill', limit=1)

     A    B   C    D
0  3.0  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  3.0 NaN  4.0
3  NaN  3.0 NaN  4.0

In [ ]:
df

     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  NaN
3  NaN  3.0 NaN  4.0

In [ ]:
df.mean()

A    3.000000
B    3.000000
C         NaN
D    1.666667
dtype: float64

In [ ]:
df.fillna(df.mean())

     A    B   C         D
0  3.0  2.0 NaN  0.000000
1  3.0  4.0 NaN  1.000000
2  3.0  3.0 NaN  1.666667
3  3.0  3.0 NaN  4.000000

In [ ]:
df.mean()['A':'B']

A    3.0
B    3.0
dtype: float64

In [ ]:
df.fillna(df.mean()['A':'B'])

     A    B   C    D
0  3.0  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  3.0  3.0 NaN  NaN
3  3.0  3.0 NaN  4.0

In [ ]:
df.mean()['D']

1.6666666666666667

In [ ]:
df.fillna(df.mean()['D'])

          A         B         C         D
0  1.666667  2.000000  1.666667  0.000000
1  3.000000  4.000000  1.666667  1.000000
2  1.666667  1.666667  1.666667  1.666667
3  1.666667  3.000000  1.666667  4.000000

In [ ]:
df.fillna(df.mean()['D'], limit=1)

          A         B         C         D
0  1.666667  2.000000  1.666667  0.000000
1  3.000000  4.000000       NaN  1.000000
2       NaN  1.666667       NaN  1.666667
3       NaN  3.000000       NaN  4.000000

In [ ]:
df.fillna(df.mean()['D'], limit=1, axis=0)

          A         B         C         D
0  1.666667  2.000000  1.666667  0.000000
1  3.000000  4.000000       NaN  1.000000
2       NaN  1.666667       NaN  1.666667
3       NaN  3.000000       NaN  4.000000

In [ ]:
df.fillna(df.mean()['D'], limit=1, axis=1)

          A    B         C    D
0  1.666667  2.0       NaN  0.0
1  3.000000  4.0  1.666667  1.0
2  1.666667  NaN       NaN  NaN
3  1.666667  3.0       NaN  4.0